### ISSUE TITLE
[BUG] Wrong Version

### ISSUE THREAD

**Issue by MainKronos** [MRtecno98/FactorioModPortal#1]
I tried to download the [Factorissimo2](https://mods.factorio.com/mod/Factorissimo2) mod and the program only downloads the first version.

When the program asks me: 'Select release to download:', and I enter the version `2.5.1`, it downloads the version `2.0.0`, the oldest version.

**Comment by MRtecno98** [comment]
Thanks for your feedback, hopefully fixed the issue
