### ISSUE TITLE
You need to set the credentials in order to download a mod

### ISSUE THREAD

**Issue by acedogblast** [MRtecno98/FactorioModPortal#4]
Does not work for non-paid accounts. When trying to download mod it said "!!! You need to set the credentials in order to download a mod !!!". Please update README.

**Comment by MRtecno98** [comment]
I think it's just a bug in the code that loads the credentials, either that or the factorio mod portal devs actually restricted the download api to work only with tokens from paid accounts. I'll check on it

**Comment by MRtecno98** [comment]
Well apparently they actually did, can't really do anything about it so this project is kinda dead...

```Downloading space-exploration... 
An error has occurred while executing the script 403 Client Error: Forbidden for url: https://mods.factorio.com/download/space-e
xploration/62ca230626212a6ce8f43026?username=MRtecno98&token=<token>
Dumping traceback below

  File "/home/flex/github/FactorioModPortal/factoriomod.py", line 465, in <module>
    start()
  File "/home/flex/github/FactorioModPortal/factoriomod.py", line 400, in start
    visited = download_recursive_mod(packet['name'], ver=None)
  File "/home/flex/github/FactorioModPortal/factoriomod.py", line 306, in download_recursive_mod
    target = download_mod(mod_info, ver=ver)
  File "/home/flex/github/FactorioModPortal/factoriomod.py", line 210, in download_mod
    request.raise_for_status()
  File "/usr/lib/python3.10/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
  HTTPError('403 Client Error: Forbidden for url: https://mods.factorio.com/download/space-exploration/62ca230626212a6ce8f43026?username=MRtecno98&token=<token>')

Press enter to terminate
```

...but in the end this was all based on an unintended feature so it was only a matter of time until it would have been fixed, it was fun while it lasted.

I'll leave this issue open if someone manages to find another way to download mods without a paid account, PRs are welcome.

**Comment by acedogblast** [comment]
@MRtecno98 Thanks for your work on this sorry that it had to end like this. For anyone who wanted to download mods here is a working website: (https://1488.me/factorio/mods/en)

**Comment by MRtecno98** [comment]
Updates on this, i actually realized i can just use the mirror hosted by @radioegor146 at https://1488.me/factorio/mods/en and download mods from there. I have absolutely no idea of how this works and i know it may break in the future but until it's here why not use it. I'll push an update soon

**Comment by radioegor146** [comment]
Hello @MRtecno98. Can you set a specific User-Agent for request to my mirrors, so I can allow them on WAFs? Thanks.

**Comment by MRtecno98** [comment]
> Hello @MRtecno98. Can you set a specific User-Agent for request to my mirrors, so I can allow them on WAFs? Thanks.

Sure thing, i'll push it now, thank you for hosting those mirrors btw :)
