### ISSUE TITLE
Error 403: Fallback mirrors got busted

### ISSUE THREAD

**Issue by Unknow0059** [MRtecno98/FactorioModPortal#5]
```403 Client Error Forbidden for URL```
It seems that the project is old and does Not work

**Comment by MRtecno98** [comment]
Yeah it seems that the guy who used to mirror the download site deleted their domain, sooo we're back at the problem in issue #4

**Comment by MRtecno98** [comment]
Yep confirmed, it also seems like the other mirror i put in last time(https://factorio-launcher-mods.storage.googleapis.com/) also started actually checking for paid accounts and does not work anymore(and that's probably why the other guy killed his tool), so for now this project is on indefinite hold. If any other source comes up from which to download the mods i'll gladly update the tool, for now it will only work with paid accounts.

I'll update the README soon
