### ISSUE TITLE
Can they be used in this program?

### ISSUE THREAD

**Issue by Werea25** [MRtecno98/FactorioModPortal#6]
There is a site https://re146.dev/factorio/mods/ where you can download mods. It uses two mirrors for downloading, these are https://official-factorio-mirror.re146.dev/ and https://mods-storage.re146.dev/. Can they be used in this program?

**Comment by MRtecno98** [comment]
Welp, i guess i could have figured it out sooner, i thought the domain was deleted but it was only moved to another one. Thanks for the heads up i'll implement it now.

**Comment by MRtecno98** [comment]
Mirrors added, thanks for the heads up
